### ****본격적으로 Numpy와 친해지기 위해서 다양한 연산을 연습해볼 예정입니다. 무작위의 데이터를 가 진 5x3의 행렬을 가지는 numpy array와 3x2 행렬을 가지는 numpy array를 만든 후 행열곱 연산을 진행해보세요.****

In [17]:
import numpy as np 

# 행렬 생성
array_1 = np.random.rand(5,3) # 5 * 3 
array_2 = np.random.rand(3,2) # 3 * 2

# 행렬곱 연산
dot = np.dot(array_1, array_2) 

print(dot, dot.shape)

[[0.68389804 0.71027963]
 [1.28724194 0.97666433]
 [0.54624578 0.70209574]
 [0.55928879 0.33729018]
 [0.38309739 0.65915864]] (5, 2)


### 두번째로는 numpy에서 자주 사용하는 concatenate 연산에 대한 미션을 수행해보겠습니다. 이제 Numpy에서 사용하는 2개의 numpy array가 있을때, 두 numpy array의 concatenate 연산을 구해보세요.

In [18]:
import numpy as np

arr1 = np.array([[5, 7], [9, 11]], float)
arr2 = np.array([[2, 4], [6, 8]], float)

concat_1 = np.concatenate((arr1, arr2), axis=0)
concat_2 = np.concatenate((arr1, arr2), axis=1)

print(concat_1)
print(concat_2)

[[ 5.  7.]
 [ 9. 11.]
 [ 2.  4.]
 [ 6.  8.]]
[[ 5.  7.  2.  4.]
 [ 9. 11.  6.  8.]]


### 3번부터 5번까지의 미션는 Numpy를 이용해서 정답값을 예측해보는 linear regression을 구현해 보는 미션입니다. 첫번째 단계로 데이터를 준비해보도록 하겠습니다. 아래와 같이 데이터가 주어져있을 때, 경사하강법을 위한 데이터를 분리해보세요.

In [19]:
import numpy as np

xy = np.array([[1.,2.,3.,4.,5.,6.],[10.,20.,30.,40.,50.,60.]])

x_train = xy[0,:]
y_train = xy[1,:]

print(x_train, x_train.shape)
print(y_train, y_train.shape)

[1. 2. 3. 4. 5. 6.] (6,)
[10. 20. 30. 40. 50. 60.] (6,)


### 경사 하강법 구현을 위해서 위에서 분리한 x_train 데이터와 계산될 weight, bias 값을 정의해보세요. 여기서 구현한 weight와 bias 는 linear regression 계산을 진행할시 직선의 기울기와 y 절편의 값이 됩니다.

In [20]:
beta_gd = np.random.rand(1)
bias = np.random.rand(1)

print(beta_gd, bias)

[0.98106089] [0.81797436]


### ### **이제 최종적으로 linear regression을 경사하강법으로 학습하는 코드를 구현해봅시다. 경사하강법 구현을 위한 학습 Loop를 구현해보세요. 최종적으로 1000회 반복했을 시에 결과를 출력하세요.**

- 단, Error는 차이의 제곱을 이용해서 계산해주세요.
- Gradient 값은 우리가 예측하는 각 변수에 대한 미분값입니다.

In [21]:
import numpy as np
import sympy as sym

xy = np.array([[1.,2.,3.,4.,5.,6.],[3.,6.,9.,12.,15.,18.]])

x_train = xy[0,:]
y_train = xy[1,:]

beta_gd = np.random.rand(1)
bias = np.random.rand(1)

learning_rate = 0.01

for i in range(1000):
    func = beta_gd * x_train + bias
    error = ((func - y_train)**2).mean()
    w_grad = sym.diff(error, beta_gd)
    b_grad = sym.diff(error, bias)
    beta_gd = beta_gd - learning_rate * w_grad
    bias = bias - learning_rate * b_grad
    
    if i%100 == 0:
        print('Epoch ({:10d}/1000) error: {:10f}, beta_gd: {:10f}, bias:{:10f}'.format(i, error, beta_gd.item(), bias.item()))

Epoch (         0/1000) error: 115.298016, beta_gd: 0.219901163683956, bias:0.0993934226283902
Epoch (       100/1000) error: 115.298015634257, beta_gd: 0.219901163683956, bias:0.0993934226283902
Epoch (       200/1000) error: 115.298015634257, beta_gd: 0.219901163683956, bias:0.0993934226283902
Epoch (       300/1000) error: 115.298015634257, beta_gd: 0.219901163683956, bias:0.0993934226283902
Epoch (       400/1000) error: 115.298015634257, beta_gd: 0.219901163683956, bias:0.0993934226283902
Epoch (       500/1000) error: 115.298015634257, beta_gd: 0.219901163683956, bias:0.0993934226283902
Epoch (       600/1000) error: 115.298015634257, beta_gd: 0.219901163683956, bias:0.0993934226283902
Epoch (       700/1000) error: 115.298015634257, beta_gd: 0.219901163683956, bias:0.0993934226283902
Epoch (       800/1000) error: 115.298015634257, beta_gd: 0.219901163683956, bias:0.0993934226283902
Epoch (       900/1000) error: 115.298015634257, beta_gd: 0.219901163683956, bias:0.0993934226283